server.port: 8888

#spring.application.name: DASHBOARD-SERVICE
#spring.config.import: optional:configserver:http://localhost:8888
#eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
#server.port: 8082

#spring.mvc.view.prefix=/WEB-INF/jsp
#spring.mvc.view.suffix=.jsp
#server.context-path=/cli

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html

currency-service:
  url: http://mapl.app
  username: devusername
  key: devkey

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  datasource:
#    url: jdbc:h2:~/test;NON_KEYWORDS=VALUE,PASSWORD;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        useUnicode: true
        show-sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8

