server.port: 8888

#spring.application.name: DASHBOARD-SERVICE
#spring.config.import: optional:configserver:http://localhost:8888
#eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
#server.port: 8082

#spring.mvc.view.prefix=/WEB-INF/jsp
#spring.mvc.view.suffix=.jsp
#server.context-path=/cli

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html

currency-service:
  url: http://mapl.app
  username: devusername
  key: devkey


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
#        web-allow-others: false  # usually false for local dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


