AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: PostApi
        SECRET_NAME: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DatabaseSecretName}
        DATABASE_ENDPOINT: !Ref DatabaseEndpoint

Parameters:
  SecurityGroupId: 
    Description: Security Group for the application
    Type: String
  Subnet1Id: 
    Description: Subnet Id for the first subnet
    Type: String
  Subnet2Id: 
    Description: Subnet Id for the second subnet
    Type: String
  DatabaseSecretName:
    Description: The name of the secret holding database credentials
    Type: String
  DatabaseEndpoint:
    Description: The endpoint of the database
    Type: String

Resources:
  PostApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: com.post.api.StreamLambdaHandler::handleRequest
      Runtime: java11
      AutoPublishAlias: postion
      SnapStart:
        ApplyOn: PublishedVersions
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref Subnet1Id
          - !Ref Subnet2Id
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DatabaseSecretName}
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
