
server.port: 8080
spring.application.name: OMNI-DB

#spring.config.import: optional:configserver:http://localhost:8888
#eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
spring.profiles.active: mysql # local  #
spring:
  main:
    allow-bean-definition-overriding: true

## Configuring info endpoint
info.app.name: REST-CRYPTOMAVEN
info.app.description: CRYPTOMAVEN CryptoCurrency Server Application
info.app.version: 1.0.0
management.info.env.enabled: false

management.endpoints.web.exposure.include: health,metrics
springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger-ui.html

spring.jmx.enabled: false
#because the javax.management.InstanceAlreadyExistsException occurs when there is an attempt to register an MBean (Managed Bean) that has already been registered. JMX is used for managing and monitoring Java applications, \
#  and Spring Boot automatically registers various MBeans for management purposes.
logging.level.org.springframework: info

spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: guest
spring.rabbitmq.password: guest

app:
  jwt-secret: e037837c23ab0fe4f59e203ece8c0ddda2c70bfd5b5319fce2af9647be43b704
  jwt-expiration-milliseconds: 604800000 # 1 week


#spring.mvc.view.prefix=/WEB-INF/jsp
#spring.mvc.view.suffix=.jsp
#server.context-path=/cli


spring.user.datasource.username: useruser
spring.user.datasource.password: abc123!!
spring.user.datasource.url: jdbc:mysql://dailytech.cdkgqkcu8kyj.us-east-1.rds.amazonaws.com:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.user.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.user.flyway.username: admin
spring.user.flyway.password: abc123!!
spring.user.flyway.url: jdbc:mysql://dailytech.cdkgqkcu8kyj.us-east-1.rds.amazonaws.com:3306/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.user.datasource.hikari.poolName: HikariPool-User


spring.category.datasource.username: categoryuser
spring.category.datasource.password: abc123!!
spring.category.datasource.url: jdbc:mysql://dailytech.cdkgqkcu8kyj.us-east-1.rds.amazonaws.com:3306/category?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.category.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.category.flyway.username: categoryadmin
spring.category.flyway.password: abc123!!
spring.category.flyway.url: jdbc:mysql://dailytech.cdkgqkcu8kyj.us-east-1.rds.amazonaws.com:3306/category?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.category.datasource.hikari.poolName: HikariPool-Category
