 
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Deploy to test
        deployment: test
         # trigger: manual  
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - echo "Deploying DAILYTECH test environment"
          - npm install
          - npm test
         
               