 
/* function getHello(){
  return 'Hello There';
}
 */ 
var march = [
  {day: '#18-03-01',
title: "Blockchain Sustainability Issues and The Double-Edged Sword",
text:"", 
type:"block"},
  {day: '#18-03-02',
  title: "Widening Circles of Mobile-App Security Risks",
  text:"",
   type:"web"},
  {day: '#18-03-03',
  title: "A Return to the Question of Guns, Germs, and Steel",
  text:"", 
  type:"soc"},
  {day: '#18-03-04',
  title: "A Return to the Question of Guns, Germs, and Steel: Part II and the Germs",
  text:"", 
  type:""},
  {day: '#18-03-05',
  title: "",
  text:"", 
  type:""},
  {day: '#18-03-06',
  title: "April 23 Implementation of the FCC Net Neutrality Laws:<br /> The Coming Battle of States&#39; versus Federal Rights",
  text:"", 
  type:"web"},
  {day: '#18-03-07',
  title: "About the April 23 Implementation of the FCC Net Neutrality Laws:<br /> The Coming Battle of States&#39; versus Federal Rights Part II",
  text:"", 
  type:"soc"},
  {day: '#18-03-08',
    title: "1.4 Million Reasons for More Women in Tech, Part II",
  text:"", 
  type:"soc"},
  {day: '#18-03-09',
  title: "Alexa, can you laugh?",
  text:"", 
  type:"web"},
  {day: '#18-03-10',
  title: "The Sharing Economy Hand-in-Hand with the Market Economy:<br /> Part I and the Race for Sustainability Solutions",
  text:"", 
  type:"web"},
  {day: '#18-03-11',
  title: "",
  text:"", 
  type:""},
  {day: '#18-03-12',
  title: "The Sharing Economy Hand-in-Hand with the Market Economy:<br /> Part II and New Forms of Trust",
  text:"",
   type:"soc"},
  {day: '#18-03-13',
  title: "The Sharing Economy Hand-in-Hand with the Market Economy:<br /> Part III and Sustainability of Shared, Distributed Ledger Types",
  text:"", 
  type:"block"},
  {day: '#18-03-14',
  title: "<h6 class=\"dailytitle chapternumber\"><i>Tou<strong>Demou</strong> tes<strong> Krates</strong></i>:<br />Strength of the People</h6>",
  text:"", 
  type:"soc"},
  {day: '#18-03-15',
  title: "",
  text:"", 
  type:""}, 
  {day: '#18-03-16',
  title: "",
  text:"", 
  type:""},
  {day: '#18-03-17',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-18',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-19',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-20',
  title: "",
  text:"", 
  type:""},
  {day: '#18-03-21',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-22',
  title: "",
  text:"", 
  type:""},
  {day: '#18-03-23',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-24',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-25',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-26',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-27',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-28',
  title: "",
  text:"",
   type:""},
  {day: '#18-03-29',
  title: "",
  text:"", 
  type:""},
  {day: '#18-03-30',
  title: "",
  text:"", 
  type:""},
  {day: '#18-03-31',
  title: "",
  text:"",
   type:""} 
];
module.exports = march; 