FROM eclipse-temurin:17.0.14_7-jdk-alpine

LABEL maintainer=thomas1.maestas@gmail.com

COPY /target/dailytech-registry-*.0.jar  dailytech-registry.jar

ENTRYPOINT ["java","-jar","dailytech-registry.jar"]




