x-to-kafka-service:
  x-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: CryptoMaven X microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

