 
/* function getHello(){
  return 'Hello There';
}
 */ 
var february = [
    {day: '#18-02-01',
  title: "",
text:"", 
type:""},
    {day: '#18-02-02',
    title: "",
    text:"", type:""},
    {day: '#18-02-03',
    title: "",
    text:"", type:""},
    {day: '#18-02-04',
    title: "",
    text:"", type:""},
    {day: '#18-02-05',
    title: "",
    text:"", type:""},
    {day: '#18-02-06',
    title: "",
    text:"", type:""},
    {day: '#18-02-07',
    title: ""},
    {day: '#18-02-08',
    title: ""},
    {day: '#18-02-09',
    title: "",
    text:"", type:""},
    {day: '#18-02-10',
    title: "",
    text:"", type:""},
    {day: '#18-02-11',
    title: "",
    text:"", type:""},
    {day: '#18-02-12',
    title: "",
    text:"", type:""},
    {day: '#18-02-13',
    title: "",
    text:"", type:""},
    {day: '#18-02-14',
    title: "",
    text:"", type:""},
    {day: '#18-02-15',
    title: "",
    text:"", type:""}, 
    {day: '#18-02-16',
    title: "",
    text:"", type:""},
    {day: '#18-02-17',
    title: "",
    text:"", type:""},
    {day: '#18-02-18',
    title: "",
    text:"", type:""},
    {day: '#18-02-19',
    title: "",
    text:"", type:""},
    {day: '#18-02-20',
    title: "",
    text:"", type:""},
    {day: '#18-02-21',
    title: "",
    text:"", type:""},
    {day: '#18-02-22',
    title: "",
    text:"", type:""},
    {day: '#18-02-23',
    title: "",
    text:"", type:""},
    {day: '#18-02-24',
    title: "",
    text:"", type:""},
    {day: '#18-02-25',
    title: "",
    text:"", type:""},
    {day: '#18-02-26',
    title: "",
    text:"", type:""},
    {day: '#18-02-27',
    title: "",
    text:"", type:""},
    {day: '#18-02-28',
    title: "",
    text:"", type:""},
    {day: '#18-02-29',
    title: "",
    text:"", type:""},
    {day: '#18-02-30',
    title: "",
    text:"", type:""},
    {day: '#18-02-31',
    title: "",
    text:"", type:""} 
  ];
  module.exports = february; 